package config

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log/slog"
	"path/filepath"
	"strings"
	"time"

	"github.com/luoye663/nxpanel/internal/agentclient"
	"github.com/luoye663/nxpanel/internal/app"
	"github.com/luoye663/nxpanel/internal/db/repo"
	"github.com/luoye663/nxpanel/internal/nginx"
)

type MigrateResponse struct {
	OperationID  string             `json:"operation_id"`
	MarkerStatus nginx.MarkerStatus `json:"marker_status"`
	Hash         string             `json:"hash"`
}

func (svc *Service) MigrateMarkers(ctx context.Context, siteID string, requestID string) (*MigrateResponse, error) {
	site, err := svc.siteRepo.GetByID(siteID)
	if err != nil {
		return nil, app.NewAppError(app.ErrInternalError, err.Error(), nil)
	}
	if site == nil {
		return nil, app.NewAppError(app.ErrNotFound, "站点不存在", nil)
	}

	currentContent, _, err := svc.agent.ReadFile(ctx, site.ConfigPath)
	if err != nil {
		return nil, app.NewAppError(app.ErrAgentUnavailable, "读取配置文件失败: "+err.Error(), nil)
	}

	if strings.Contains(string(currentContent), nginx.MarkerSiteStart) {
		return nil, app.NewAppError(app.ErrConflict, "配置文件已包含标识块，无需迁移", nil)
	}
	ensureIncludePaths(site)

	newConfig, err := convertOldToNewMarkers(site, string(currentContent))
	if err != nil {
		return nil, app.NewAppError(app.ErrInternalError, "转换标识块失败: "+err.Error(), nil)
	}

	opID := app.NewOperationID()
	_ = svc.opRepo.Create(&repo.Operation{
		ID: opID, Action: "site.migrate_markers", TargetType: "site", TargetID: siteID,
		Status: "pending", RequestID: requestID, Actor: "admin",
		Message:   fmt.Sprintf("迁移标识块 站点 %s", site.PrimaryDomain),
		CreatedAt: time.Now().UTC().Format(time.RFC3339),
	})

	_, agentErr := svc.agent.ApplyTransaction(ctx, &agentclient.TransactionRequest{
		OperationID: opID,
		Changes: []agentclient.FileChangeRequest{
			{Type: "mkdir", Path: filepath.Dir(site.HotlinkPath), Perm: 0755},
			{Type: "mkdir", Path: filepath.Dir(site.AccessLimitPath), Perm: 0755},
			{Type: "write", Path: site.HotlinkPath, ContentBase64: base64.StdEncoding.EncodeToString([]byte("# generated by nxpanel\n")), Perm: 0644},
			{Type: "write", Path: site.AccessLimitPath, ContentBase64: base64.StdEncoding.EncodeToString([]byte("")), Perm: 0644},
			{
				Type:          "write",
				Path:          site.ConfigPath,
				ContentBase64: base64.StdEncoding.EncodeToString([]byte(newConfig)),
				Perm:          0644,
			},
		},
		TestNginx:   true,
		ReloadNginx: site.Status == "enabled",
	})
	if agentErr != nil {
		_ = svc.opRepo.UpdateError(opID, "failed", app.ErrAgentUnavailable, agentErr.Error(), "")
		return nil, app.NewAppError(app.ErrAgentUnavailable, "迁移标识块失败: "+agentErr.Error(), nil)
	}

	site.MarkerVersion = 1
	_ = svc.siteRepo.Update(site)
	_ = svc.opRepo.UpdateStatus(opID, "success")

	markerStatus := nginx.ValidateRequiredMarkers([]byte(newConfig), nginx.RequiredSiteMarkers())

	slog.Info("标识块迁移成功", "site_id", siteID, "operation_id", opID)

	return &MigrateResponse{
		OperationID:  opID,
		MarkerStatus: markerStatus,
		Hash:         nginx.HashContent([]byte(newConfig)),
	}, nil
}

func ensureIncludePaths(site *repo.Site) {
	panelDir := filepath.Dir(filepath.Dir(site.RewritePath))
	if site.AccessLimitPath == "" {
		site.AccessLimitPath = filepath.Join(panelDir, "access-limit", site.PrimaryDomain+".conf")
	}
	if site.HotlinkPath == "" {
		site.HotlinkPath = filepath.Join(panelDir, "hotlink", site.PrimaryDomain+".conf")
	}
}

type migrateData struct {
	SiteID          string
	PrimaryDomain   string
	HTTPPort        int
	ServerNames     string
	RootPath        string
	IndexFiles      string
	AccessLogPath   string
	ErrorLogPath    string
	RewritePath     string
	AccessLimitPath string
	HotlinkPath     string
}

func convertOldToNewMarkers(site *repo.Site, oldConfig string) (string, error) {
	var domains []string
	json.Unmarshal([]byte(site.DomainsJSON), &domains)
	serverNames := strings.Join(domains, " ")

	_ = oldConfig

	data := &migrateData{
		SiteID:          site.ID,
		PrimaryDomain:   site.PrimaryDomain,
		HTTPPort:        site.HTTPPort,
		ServerNames:     serverNames,
		RootPath:        site.RootPath,
		IndexFiles:      site.IndexFiles,
		AccessLogPath:   site.AccessLogPath,
		ErrorLogPath:    site.ErrorLogPath,
		RewritePath:     site.RewritePath,
		AccessLimitPath: site.AccessLimitPath,
		HotlinkPath:     site.HotlinkPath,
	}

	ts := nginx.GetTemplateStore()
	return nginx.ExecuteTemplateString(ts.MigrateSite, data)
}
