package geoaccess

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/netip"
	"path/filepath"
	"sort"
	"strings"

	"github.com/luoye663/nxpanel/internal/db/repo"
)

const maxRenderedConfigBytes = 64 * 1024 * 1024

type renderedSite struct {
	SiteID      string
	Variable    string
	SitePath    string
	SiteContent string
	AllowPath   string
	AllowBody   string
	DenyPath    string
	DenyBody    string
	Hash        string
}

type renderedConfig struct {
	GlobalPath    string
	GlobalContent string
	Sites         map[string]*renderedSite
}

func validAction(action string) bool {
	return action == ActionAllow || action == ActionDeny403 || action == ActionDeny444
}

func normalizeCountries(values []string) ([]string, error) {
	seen := make(map[string]struct{}, len(values))
	result := make([]string, 0, len(values))
	for _, value := range values {
		code := strings.ToUpper(strings.TrimSpace(value))
		if len(code) != 2 || code[0] < 'A' || code[0] > 'Z' || code[1] < 'A' || code[1] > 'Z' {
			return nil, fmt.Errorf("无效国家代码: %s", value)
		}
		if _, ok := seen[code]; ok {
			continue
		}
		seen[code] = struct{}{}
		result = append(result, code)
	}
	sort.Strings(result)
	if len(result) == 0 {
		return nil, fmt.Errorf("请至少选择一个国家或地区")
	}
	return result, nil
}

func compileCountryActions(rules []*repo.SiteGeoRule) map[string]string {
	result := make(map[string]string)
	for _, rule := range rules {
		if !rule.Enabled {
			continue
		}
		for _, country := range repo.ParseJSONStringSlice(rule.CountriesJSON) {
			country = strings.ToUpper(country)
			if _, exists := result[country]; !exists {
				result[country] = rule.Action
			}
		}
	}
	return result
}

func variableSuffix(siteID string) string {
	sum := sha256.Sum256([]byte(siteID))
	return hex.EncodeToString(sum[:6])
}

func renderIPEntries(entries []string, value string) (string, error) {
	seen := make(map[string]struct{}, len(entries))
	normalized := make([]string, 0, len(entries))
	for _, entry := range entries {
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		if prefix, err := netip.ParsePrefix(entry); err == nil {
			entry = prefix.Masked().String()
		} else if addr, err := netip.ParseAddr(entry); err == nil {
			entry = addr.String()
		} else {
			return "", fmt.Errorf("无效 IP/CIDR: %s", entry)
		}
		if _, exists := seen[entry]; exists {
			continue
		}
		seen[entry] = struct{}{}
		normalized = append(normalized, entry)
	}
	sort.Strings(normalized)
	var b strings.Builder
	b.WriteString("# Generated by nxPanel.\n")
	for _, entry := range normalized {
		fmt.Fprintf(&b, "%s %s;\n", entry, value)
	}
	return b.String(), nil
}

func renderConfiguration(panelDir string, trustedProxies []string, cache *countryCache,
	settings []*repo.SiteGeoSettings, rulesBySite map[string][]*repo.SiteGeoRule,
	ipRulesBySite map[string][]*repo.SiteIPWhitelistRule) (*renderedConfig, error) {
	result := &renderedConfig{GlobalPath: filepath.Join(panelDir, "conf.d", "10-nxpanel-geo-access.conf"), Sites: make(map[string]*renderedSite)}
	if len(settings) == 0 {
		return result, nil
	}
	var global strings.Builder
	global.WriteString("# Generated by nxPanel. Do not edit.\n")
	for _, proxy := range trustedProxies {
		fmt.Fprintf(&global, "set_real_ip_from %s;\n", proxy)
	}
	if len(trustedProxies) > 0 {
		global.WriteString("real_ip_header X-Forwarded-For;\nreal_ip_recursive on;\n")
	}
	global.WriteString("map $uri $nx_geo_system_exempt {\n    default 0;\n    ~^/\\.well-known/acme-challenge/ 1;\n}\n")
	for _, setting := range settings {
		if !setting.Enabled {
			continue
		}
		suffix := variableSuffix(setting.SiteID)
		countryVar := "$nx_geo_country_" + suffix
		denyVar := "$nx_geo_ip_deny_" + suffix
		allowVar := "$nx_geo_ip_allow_" + suffix
		actionVar := "$nx_geo_action_" + suffix
		actions := compileCountryActions(rulesBySite[setting.SiteID])
		unknownAction := setting.DefaultAction
		if value, ok := actions["ZZ"]; ok {
			unknownAction = value
		}
		fmt.Fprintf(&global, "geo %s {\n    default %s;\n", countryVar, unknownAction)
		countries := make([]string, 0, len(cache.Networks))
		for country := range cache.Networks {
			countries = append(countries, country)
		}
		sort.Strings(countries)
		for _, country := range countries {
			action := setting.DefaultAction
			if value, ok := actions[country]; ok {
				action = value
			}
			if action == unknownAction {
				continue
			}
			for _, network := range cache.Networks[country] {
				fmt.Fprintf(&global, "    %s %s;\n", network, action)
			}
		}
		global.WriteString("}\n")

		allowPath := filepath.Join(panelDir, "geo-access", "ip", setting.SiteID+"-allow.conf")
		denyPath := filepath.Join(panelDir, "geo-access", "ip", setting.SiteID+"-deny.conf")
		var allowEntries, denyEntries []string
		for _, rule := range ipRulesBySite[setting.SiteID] {
			if !rule.Enabled {
				continue
			}
			if strings.EqualFold(rule.RuleType, "deny") {
				denyEntries = append(denyEntries, repo.ParseJSONStringSlice(rule.IPsJSON)...)
			} else {
				allowEntries = append(allowEntries, repo.ParseJSONStringSlice(rule.IPsJSON)...)
			}
		}
		allowBody, err := renderIPEntries(allowEntries, "1")
		if err != nil {
			return nil, err
		}
		denyBody, err := renderIPEntries(denyEntries, "1")
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&global, "geo %s {\n    default 0;\n    include %s;\n}\n", denyVar, denyPath)
		fmt.Fprintf(&global, "geo %s {\n    default 0;\n    include %s;\n}\n", allowVar, allowPath)
		fmt.Fprintf(&global, "map \"$nx_geo_system_exempt:%s:%s:%s\" %s {\n", denyVar, allowVar, countryVar, actionVar)
		global.WriteString("    ~^[01]:1: deny_403;\n    ~^[01]:0:1: allow;\n    ~^1:0:0: allow;\n")
		fmt.Fprintf(&global, "    default %s;\n}\n", countryVar)

		sitePath := filepath.Join(panelDir, "geo-access", "sites", setting.SiteID+".conf")
		siteBody := fmt.Sprintf("# Generated by nxPanel. Do not edit.\nif (%s = deny_403) { return 403; }\nif (%s = deny_444) { return 444; }\n", actionVar, actionVar)
		hashInput, _ := json.Marshal(struct {
			Default string
			Rules   []*repo.SiteGeoRule
			Actions map[string]string
			Cache   int64
			Proxies []string
			AllowIP string
			DenyIP  string
		}{
			setting.DefaultAction, rulesBySite[setting.SiteID], actions, cache.BuildEpoch, trustedProxies, allowBody, denyBody})
		sum := sha256.Sum256(hashInput)
		result.Sites[setting.SiteID] = &renderedSite{SiteID: setting.SiteID, Variable: actionVar,
			SitePath: sitePath, SiteContent: siteBody, AllowPath: allowPath, AllowBody: allowBody,
			DenyPath: denyPath, DenyBody: denyBody, Hash: hex.EncodeToString(sum[:])}
		if global.Len() > maxRenderedConfigBytes {
			return nil, fmt.Errorf("生成的地域配置超过 64 MiB 上限")
		}
	}
	result.GlobalContent = global.String()
	return result, nil
}

const geoIncludeStart = "# NXPANEL-GEO-ACCESS-START"
const geoIncludeEnd = "# NXPANEL-GEO-ACCESS-END"

func patchAccessLimit(content []byte, includePath string, enabled bool) []byte {
	text := string(content)
	for {
		start := strings.Index(text, geoIncludeStart)
		if start < 0 {
			break
		}
		endRel := strings.Index(text[start:], geoIncludeEnd)
		if endRel < 0 {
			text = strings.TrimSpace(text[:start]) + "\n"
			break
		}
		end := start + endRel + len(geoIncludeEnd)
		text = strings.TrimSpace(text[:start]+text[end:]) + "\n"
	}
	if enabled {
		if strings.TrimSpace(text) != "" && !strings.HasSuffix(text, "\n") {
			text += "\n"
		}
		text += fmt.Sprintf("\n%s\ninclude %s;\n%s\n", geoIncludeStart, includePath, geoIncludeEnd)
	}
	return []byte(strings.TrimLeft(text, "\n"))
}
